### ISSUE TITLE
一直报错，不知道是啥情况

### ISSUE THREAD

**Issue by lucsus** [Arryboom/MasscanForWindows#1]
大佬，我这个一直报错，麻烦您给看下，是不是应该有个编译的msvcr110d.dll文件？我把packet.dll和wpcap.dll都复制到当前文件夹下也不行。请您帮忙看下如何处理？谢谢
![qq 20190112113130](https://user-images.githubusercontent.com/28680447/51068758-aeaf3b80-165d-11e9-959a-72aed30bf2ce.png)

**Comment by Arryboom** [comment]
> 大佬，我这个一直报错，麻烦您给看下，是不是应该有个编译的msvcr110d.dll文件？我把packet.dll和wpcap.dll都复制到当前文件夹下也不行。请您帮忙看下如何处理？谢谢
> ![qq 20190112113130](https://user-images.githubusercontent.com/28680447/51068758-aeaf3b80-165d-11e9-959a-72aed30bf2ce.png)

见
https://blog.csdn.net/hackerie/article/details/78651725?locationNum=3&fps=1
如果发现报错，类似\devices\npf adapter，推荐把虚拟网卡关闭。

就像

FAIL:failed to detect IP of interface “Device\NPF_{“

只留下当前使用的无线网卡或本地网卡(将另一个禁用，只留下当前使用的那一个)。

同时，也可以参考：

http://www.4hou.com/penetration/6173.html
